### PR TITLE
Diploma solution

### PR DESCRIPTION
**Pull request by sanyalyao**
Made solution: made skeleton, added tests from homework just to check if everything works, added bussines objects and core for API, UI and runsettings

### CODE REVIEW

**Review by VladimirVolkovVD — CHANGES_REQUESTED** [review]
Good job, needs some fixes

**Comment by sanyalyao** [comment]
FIRST UPDATE

Fixed API models, baseService, helpers, UI Pages, browser settings, runsettings

Added element PushMessage, negative creation contact test

SECOND UPDATE

Fixed CreationHelper, GroupModel, Contact pages, Group pages
Deleted GroupHelper
Added Access type, new negative tests for contacts and groups

**Comment by sanyalyao** [comment]
Added:
logging,
allure reporting,
parallel tests initialization,
allure attributes in tests and bussines objects

**Comment by sanyalyao** [comment]
Code refactoring

Changed:
runsettings,
names of some methods

Added:
Classes with steps,
Method GoToGroupPageByGroupName,
Method EditGroupByGroupName,
Method GoToContactPageByContactName

**Pull request merged**
